[project]
name = "emg-gui"
version = "0.1.0"
description = ""
authors = [
    {name = "Nikhil Pareek", email = "nikhilpareek149@gmail.com"}
]
maintainers = [
    {name = "Nikhil Pareek", email = "nikhilpareek149@gmail.com"}
]
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "brainflow==5.16.0",
    "dvg-ringbuffer==1.1.0",
    "freetype-py==2.5.1",
    "librosa==0.11.0",
    "matplotlib==3.9.4",
    "moderngl==5.12.0",
    "numpy==1.26.4",
    "PyQt5==5.15.11",
    "PyQt5-Qt5==5.15.2; sys_platform == 'win32'",
    "PyQt5-Qt5==5.15.19; sys_platform != 'win32'",
    "PyQt5-sip==12.17.1",
    "pyrr==0.10.3",
    "pyserial==3.5",
    "setuptools==80.10.2",
    "typing-extensions==4.16.0",
]

[project.urls]
Homepage = "https://github.com/pareeknikhil/emg-gui"
Documentation = "https://pareeknikhil.github.io/"
Issues = "https://github.com/pareeknikhil/emg-gui/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
emg-gui = "emg_gui.app:main"

[tool.poetry]
packages = [{ include = "emg_gui", from = "src" }]
include = [
    { path = "src/emg_gui/visualizer/shaders/**/*.glsl", format = ["sdist", "wheel"] },
    { path = "src/emg_gui/config/*.ttf", format = ["sdist", "wheel"] },
]