name: release

permissions:
  contents: read

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

    branches:
      - "feature/**"

env:
  PACKAGE_NAME: "<PACKAGE_NAME>"
  OWNER: "<OWNER>"

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Print package and owner
        id: print
        run: |
          echo "package name is $PACKAGE_NAME"
          echo "owner is $OWNER"
