name: Super-Linter

on:
  # Run on pushes to feature branch
  push:
    branches:
      - "feature/**"

  # Run when a PR targets main/master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TRIVY: "false"
          VALIDATE_PYTHON_RUFF_FORMAT: "false"
          VALIDATE_PYTHON_ISORT: "false"

          # Lint the entire repository on every run
          VALIDATE_ALL_CODEBASE: true
