name: Super-Linter

on:
  # Run on pushes to feature branch
  push:
    branches:
      - "feature/**"

  # Run when a PR targets main/master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Lint the entire repository on every run
          VALIDATE_ALL_CODEBASE: true

          # Do not lint files ignored by .gitignore
          IGNORE_GITIGNORED_FILES: true
